version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    labels:
      NAME: "rabbitmq"
    network_mode: "host"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: "host"

  grafana:
    image: grafana/grafana
    network_mode: "host"
    depends_on:
      - prometheus
