{
 "title": "Websocket-Server",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Average Sessionduration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(active_websocket_connection_durations_histogram_sum[$__range])) / sum(rate(active_websocket_connection_durations_histogram_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Active Workers ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_workers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sessionduration Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(active_websocket_connection_durations_histogram_bucket[10m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Websocket Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "active_websocket_connections{instance=\"localhost:9091\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Workers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    { "expr": "active_workers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Response Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(response_times_histogram_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "received_messages_total{instance=\"localhost:9091\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}